### ISSUE TITLE
Trigger name

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#1191] opened 2021-03-17 10:40 UTC
**Describe the bug**
Trigger name are generated from backend as of now, with time being calculated as per organization's default timezone. We need to update same so that the time displayed on trigger name will be based on local timezone
![image](https://user-images.githubusercontent.com/40158831/111455041-57282100-873b-11eb-8d97-f5272863c9c7.png)

**Comment by mdshamoon** [comment] 2021-03-17 10:43
Duplicate of #1189

**Closed** 2021-03-17 10:43 UTC
