### ISSUE TITLE
Error in console when hovered on the messages in chat

### ISSUE THREAD

**Issue by kurund** [glific/glific-frontend#130] opened 2020-07-03 15:20 UTC
**Describe the bug**
Error in console when hovered on the messages in chat

**To Reproduce**
1. Go to chat
2. Hover on the messages section
3. You will see the error in the browser console.

**Expected behavior**
There should not be any error

**Screenshots**
![Screenshot 2020-07-03 at 8 40 36 PM](https://user-images.githubusercontent.com/151481/86482071-d2dd6b80-bd6e-11ea-8ba1-1dd837c54a30.jpg)

**Desktop (please complete the following information):**
 - Browser: [Chrome]
 - Version [83]

**Comment by rathorevaibhav** [comment] 2020-07-17 13:53
**Why is this error happening?**
Earlier React uses findDOMNode to find the inner DOM element of a component. Let us take the case of an input component where an input element is wrapped to get input. To reference the input element within the component we can use findDOMNode.
https://reactjs.org/docs/react-dom.html#finddomnode

Now React has changed its core concept and has introduced Refs or references where a component can pass reference to its child components to get to the DOM node. The preferred way now is to access DOM node through Refs.
https://reactjs.org/docs/refs-and-the-dom.html

Material UI used to work on the findDOMNode concept and is now moving to Refs slowly. So we can hope to see these errors removed in the future updates of material UI where they will use Refs instead of findDOMNode.
Further progress can be found here: https://github.com/mui-org/material-ui/issues/13394

I believe the easiest way right now is to wait for some time while Material UI library gets updated and resolves this error.

**Comment by rathorevaibhav** [comment] 2020-12-07 06:30
Material UI's latest version v5 is in alpha right now. I checked with that and the issue is no longer coming up. However, considering it is in alpha, let's wait for some time until we have a stable release there.

To be targeted later.

**Comment by rathorevaibhav** [comment] 2021-02-23 13:34
This is no longer happening. Closing.

**Closed by rathorevaibhav** 2021-02-23 13:34 UTC
Labels: on hold
