### ISSUE TITLE
Session timer, faster update

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#389] opened 2020-08-31 11:15 UTC
- [x] Can we have a faster response for showing the session timer, right now explicit loading is required
![image](https://user-images.githubusercontent.com/16714604/91699021-46460280-eb91-11ea-8ab8-d05980addbf0.png)

**Comment by kurund** [comment] 2020-09-01 03:59
@abhi1203 Currently, we are refreshing it every minute. Not sure if we need to make it faster.

**Comment by abhi1203** [comment] 2020-09-01 12:40
@kurund alright. It may be more of a testing feedback because when i triggered the message, i was expecting the timer to show up sooner. Maybe with real use case it would be fine.

**Comment by kurund** [comment] 2020-09-01 12:49
No action is needed on this. Closing after discussion with @abhi1203

**Comment by rathorevaibhav** [comment] 2020-09-03 15:50
Reopening this as the issue is still present and not fixed.

Currently we are refreshing the timer after every 60 seconds on the basis of lastMessageAt column of contact from the search query.
The column lastMessageAt does not update when we get a new message from subscription. So we don't get updated time in the timer when we receive a new message.
So we have to explicitly change the lastMessageAt of contact in the cache when we receive a new message.

**Closed** 2020-09-04 11:03 UTC
Labels: needed for release
