### ISSUE TITLE
Simulator is duplicating all messages

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#891] opened 2021-01-07 10:19 UTC
![image](https://user-images.githubusercontent.com/16714604/103881045-ed1e4a80-50ff-11eb-8b2f-ca6647ddffb9.png)

- [ ] - duplicate messages
- [ ] - Sometimes it does not trigger the messages
- [ ] - Logout issues

**Comment by mohitsharma-22** [comment] 2021-01-18 12:52
The simulator doesn't respond to the messages. The user needs to logout and login again to make it work. The issue is not consistent. The behavior is intermittent.

<img width="1028" alt="Simulator_doesn't work" src="https://user-images.githubusercontent.com/16541548/104917971-1ec5ca00-59ba-11eb-8641-1dd56a6a9056.png">

**Comment by mohitsharma-22** [comment] 2021-01-19 04:24
Other feedback.
1. Simulator messages should auto-scroll at the bottom at the start of it. Currently, it stays in the middle and the user needs to scroll at the bottom to see the current messages.
2. 
<img width="1037" alt="Simulator scroll" src="https://user-images.githubusercontent.com/16541548/104987652-36de2d80-5a3c-11eb-8478-fad13b075c83.png">

**Comment by dlobo** [comment] 2021-02-23 18:17
Closing this issue since its covers quite a few issues and some of them are open (multiple messages etc). lets ensure each issue is for one specific problem only rather than a set of problems doing forward

**Closed by dlobo** 2021-02-23 18:17 UTC
Labels: Priority : High, bug
