### ISSUE TITLE
Update message when we start a flow for the collection.

### ISSUE THREAD

**Issue by pankaj-ag** [glific/glific-frontend#1759] opened 2021-11-24 13:48 UTC
We recently made some changes in the start group flow API and tried to make it more scalable. 
Now when you start a flow for the group, instead of sending the messages immediately it will send the messages in chucks every minute. 

The first batch will be scheduled after a min when you start the flow for the group. 

So we need to update the flash message accordingly when we start a message for the group. 

![image](https://user-images.githubusercontent.com/10670690/143250332-e00a8d3a-d205-4ff7-9e1e-8c9e0656d178.png)

**Comment by mdshamoon** [comment] 2021-11-25 03:51
Duplicate of #1750

**Closed by mdshamoon** 2021-11-25 03:51 UTC
Labels: enhancement, design
