### ISSUE TITLE
Error while submitting an hsm template

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#1048] opened 2021-02-22 13:58 UTC
**Describe the bug**
Avanti folks reported that they get an error while submitting the HSM template

**To Reproduce**
1. Enter all the template details and submit 

**Expected behavior**
Either relevant errors should show up or the template should be sent for approval without the error

**Screenshots**
![image](https://user-images.githubusercontent.com/16714604/108718034-fe9ea300-7543-11eb-991d-1e568bb27cd2.png)

Also need design inputs for this. the modal doesn't look too good.

**Comment by mdshamoon** [comment] 2021-02-23 13:35
@abhi1203 we had a call with Avanti folks and the issue is not getting replicated. We have asked them to let us know if the issue persists again.

**Comment by rathorevaibhav** [comment] 2021-02-24 12:21
Closing as not being able to replicate. Will reopen if comes again.

**Closed by rathorevaibhav** 2021-02-24 12:21 UTC
Labels: bug
