### ISSUE TITLE
Ticketing System: UI Fixes

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2626] opened 2023-11-20 09:12 UTC
**Describe the bug**
Need padding in issue column so there is no overlapping text

**Screenshots**
<img width="1195" alt="image" src="https://github.com/glific/glific-frontend/assets/40158831/f9e170a0-ee14-40d0-bb4c-c58bc87213bf">

**Comment by mdshamoon** [comment] 2023-11-20 09:38
Duplicate of #2609. Will go in today's build

**Closed by mdshamoon** 2023-11-20 09:38 UTC
Labels: bug
