### ISSUE TITLE
Simulator is not showing the responses while doing conversation

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#2056] opened 2022-05-09 11:11 UTC
Steps to reproduce.
1. Open a simulator. 
2. Respond to the question. It will not be visible on the simulator. It gives the feeling the simulator is not working.
3. Close the simulator. and click on the preview button again.
4. The earlier response posted will be visible on the simulator.
5. Again need to repeat steps from 2 to 4  for the next response.

Screenshot.
1.
<img width="1563" alt="Screenshot 2022-05-09 at 3 25 45 PM" src="https://user-images.githubusercontent.com/16541548/167399085-7ceb00f6-aeb4-4a90-8f84-1440bbca1eb8.png">

2.
<img width="1530" alt="Screenshot 2022-05-09 at 3 25 57 PM" src="https://user-images.githubusercontent.com/16541548/167399128-5ba5f70f-bb08-46e7-a106-120886d85c13.png">

3.
<img width="1547" alt="Screenshot 2022-05-09 at 3 26 05 PM" src="https://user-images.githubusercontent.com/16541548/167399190-4c4a54fd-b811-40fd-8e9e-f5d77e0d933c.png">

4.
<img width="1548" alt="Screenshot 2022-05-09 at 3 26 49 PM" src="https://user-images.githubusercontent.com/16541548/167399231-9ec2af79-6cc3-411c-9b5f-1dcb6c7f62fa.png">

**Comment by mdshamoon** [comment] 2022-08-17 07:56
Duplicate of #1905

**Closed by mdshamoon** 2022-08-17 07:56 UTC
Labels: bug
