### ISSUE TITLE
Not Opted In discrepancy

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2041] opened 2022-04-26 06:02 UTC
**Describe the bug**
Contacts opted in using Glific opt-in API are still showing non opted in.

**Expected behavior**
We should be able to send messages to contacts from Glific who are already opted into the bot

**Screenshots**
<img width="412" alt="image" src="https://user-images.githubusercontent.com/40158831/165232168-d52d6cca-3fb6-4465-a8e3-a2fba1c11828.png">

**Comment by mdshamoon** [comment] 2022-04-26 06:03
Duplicate of #2035

**Closed by mdshamoon** 2022-04-26 06:03 UTC
