### ISSUE TITLE
Templates: Raise to Gupshup

### ISSUE THREAD

**Issue by AkhileshNegi** [glific/glific-frontend#2651] opened 2023-12-04 14:01 UTC
**Is your feature request related to a problem? Please describe.**
 Target issue is #2964 

**Describe the solution you'd like**
Backend API are already there, we need to add frontend for same

**Comment by mdshamoon** [comment] 2023-12-04 17:09
Duplicate of #2512

**Closed by mdshamoon** 2023-12-04 17:09 UTC
Labels: enhancement
