### ISSUE TITLE
Duplicate collection name

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#420] opened 2020-09-03 14:20 UTC
If a collection name already exists, can we show the error on the previous modal itself?
![image](https://user-images.githubusercontent.com/16714604/92125892-2c205480-ee1d-11ea-99b5-83fe5e2e3151.png)

On this screen when users click save, the error can be shown like other errors below the title input field
![image](https://user-images.githubusercontent.com/16714604/92126086-5ffb7a00-ee1d-11ea-8513-b023cdb3111d.png)

**Comment by kurund** [comment] 2020-09-03 17:14
This is duplicate of #412

**Closed** 2020-09-04 12:03 UTC
