### ISSUE TITLE
Simulator is not having option to send location

### ISSUE THREAD

**Issue by mohitsharma-22** [glific/glific-frontend#1888] opened 2022-02-01 14:02 UTC
**Is your feature request related to a problem? Please describe.**
One of the NGO users reported, there is no option to send location in the simulator to test.
To test, the user needs to publish the flow and the user doesn't want to do that.

<img width="303" alt="Screenshot_2022-02-01_at_1 40 32_PM" src="https://user-images.githubusercontent.com/16541548/151982400-93b80169-73d7-4233-bd29-6cea739afc0b.png">

**Comment by mdshamoon** [comment] 2022-02-08 08:36
Design file link: https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/QbZEdj7

**Comment by mdshamoon** [comment] 2022-02-08 12:04
Duplicate of #1904

**Closed by mdshamoon** 2022-02-08 12:04 UTC
Labels: enhancement
